app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('tasks/', include('tasks.urls')),
    path('weather/', include('weather.urls')),
    path('shorturl/', include('shorturl.urls')),
    path('polls/', include('polls.urls')),
]

shorturl/urls.py
from django.urls import path
from . import views

app_name = 'shorturl'

urlpatterns = [
    path('', views.shorten_url, name='index'),
    path('<str:short_code>/', views.redirect_to_original, name='redirect_to_original'),
]

shorturl/models.py
import string
import random
from django.db import models

def generate_short_code():
    """Generate a random 6-character code for the short URL."""
    return ''.join(random.choices(string.ascii_letters + string.digits, k=6))

class ShortURL(models.Model):
    original_url = models.URLField()
    short_code = models.CharField(max_length=6, unique=True, default=generate_short_code)

    def __str__(self):
        return f"{self.short_code} -> {self.original_url}"

shorturl/forms.py
from django import forms

class URLForm(forms.Form):
    original_url = forms.URLField(label="Enter URL to shorten", widget=forms.URLInput(attrs={'placeholder': 'URL to shorten'}))

shorturl/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import ShortURL
from .forms import URLForm

def shorten_url(request):
    if request.method == "POST":
        form = URLForm(request.POST)
        if form.is_valid():
            original_url = form.cleaned_data['original_url']
            short_url = ShortURL.objects.create(original_url=original_url)
            return render(request, 'shorturl/success.html', {'short_url': short_url})
    else:
        form = URLForm()
    return render(request, 'shorturl/index.html', {'form': form})

def redirect_to_original(request, short_code):
    short_url = get_object_or_404(ShortURL, short_code=short_code)
    return redirect(short_url.original_url)

shorturl/templates/shorturl/app.html
{% extends 'base.html' %}

{% block content %}
  <div class="container bg-secondary px-0 mt-3" style="max-width: 500px;">
    <div class="container bg-primary text-center">
      <h1 class="p-3 m-0">Shorten URL app</h1>
    </div>
    <div class="container py-3">
      {% block shorturl %}
        <!-- shorturl -->
      {% endblock %}
    </div>
  </div>
{% endblock %}

shorturl/templates/shorturl/index.html
{% extends 'shorturl/app.html' %}
{% load django_bootstrap5 %}
{% block shorturl %}
  <div class="container">
    <form method="post" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% bootstrap_button button_type='submit' content='Submit' %}
    </form>
  </div>
{% endblock %}

shorturl/templates/shorturl/success.html
{% extends "shorturl/app.html" %}

{% block shorturl %}
<h1>Your URL has been shortened!</h1>
<p>Short URL: <a href="{{ short_url.short_code }}">{{ request.build_absolute_uri }}{{ short_url.short_code }}</a></p>
<a href="{% url 'shorturl:index' %}" class="btn btn-primary">Shorten another URL</a>
{% endblock %}