app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('tasks/', include('tasks.urls')),
    path('weather/', include('weather.urls')),
    path('shorturl/', include('shorturl.urls')),
    path('polls/', include('polls.urls')),
]

tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.list, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/toggle/', views.toggle_task_status, name='toggle_task_status'),
]

tasks/models.py
from django.db import models

class Task(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "Task #" + str(self.pk) + ": " + self.title

tasks/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

tasks/views.py
from django.shortcuts import render, redirect
from .models import Task
from .forms import TaskForm
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

def list(request):
    tasks = Task.objects.all()
    return render(request, 'tasks/list.html', {'tasks': tasks})

def detail(request, id):
    task = Task.objects.get(id=id)
    return render(request, 'tasks/detail.html', {'task': task})

def create(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('tasks:index')
    else:
        form = TaskForm()
    return render(request, 'tasks/create.html', {'form': form})

def update(request, id):
    task = Task.objects.get(id=id)
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        task.title = title
        task.description = description
        task.save()
        return redirect('tasks:index')
    return render(request, 'tasks/update.html', {'task': task})

def delete(request, id):
    task = Task.objects.get(id=id)
    task.delete()
    return redirect('tasks:index')

@csrf_exempt
def toggle_task_status(request, id):
    if request.method == 'POST':
        task = Task.objects.get(id=id)
        task.completed = not task.completed
        task.save()
        return JsonResponse({'completed': task.completed})

tasks/templates/tasks/create.html
{% extends 'tasks/dash.html' %}
{% load django_bootstrap5 %}
{% block tasks %}
  <div class="container">
    <h1>Create a New Task</h1>
    <form method="post" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% bootstrap_button button_type='submit' content='Create task' %}
    </form>
  </div>
{% endblock %}

tasks/templates/tasks/dash.html
{% extends 'base.html' %}

{% block content %}
  <div class="container bg-secondary px-0 mt-3" style="max-width: 500px;">
    <div class="container bg-primary d-flex justify-content-between align-items-center">
      <a href="{% url 'tasks:index' %}" class="btn btn-primary border border-white"><i class="bi bi-list"></i></a>
      <h1  class="p-3 m-0">Task app</h1>
      <div>
        <a href="{% url 'tasks:create' %}" class="btn btn-success border border-white"><i class="bi bi-plus"></i></a>
      </div>
    </div>
    <div class="container py-3">
      {% block tasks %}
        <!-- tasks -->
      {% endblock %}
    </div>
  </div>
{% endblock %}

tasks/templates/tasks/detail.html
{% extends 'tasks/dash.html' %}

{% block tasks %}
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h1 class="mb-0">{{ task.title }}</h1>
            <a href="{% url 'tasks:delete' task.id %}" class="btn btn-danger">
                <i class="bi bi-trash-fill"></i>
            </a>
        </div>
        <div class="card-body">
            <p>{{ task.description }}</p>
            <p>Completed: {{ task.completed }}</p>
            <p>Created: {{ task.created_at }}</p>
            <p>Updated: {{ task.updated_at }}</p>
        </div>
    </div>
{% endblock %}

tasks/templates/tasks/list.html
{% extends 'tasks/dash.html' %}

{% block tasks %}
    <div class="list-group list-group-flush">
      {% for task in tasks %}
      <li class="list-group-item">
        <div class="d-flex justify-content-between align-items-center">
          <a href="{% url 'tasks:detail' task.id %}" class=" list-group-item-action"><h3>{{ task.title }}</h3><p>{{ task.description }}</p></a>
          <div class="form-check">
            <i class="bi {% if task.completed %}
                  bi-check-square
              {% else %} 
                  bi-square
              {% endif %}"
              id="taskCompleted{{ task.id }}"
              onclick="toggleTaskStatus({{ task.id }})">
            </i>
          </div>
        </div>
      </li>
      {% empty %}
      <li class="list-group-item">
        <a href="#" class="list-group-item list-group-item-action">No tasks available.</a>
      </li>
      {% endfor %}
    </div>
{% endblock %}